services: 

    stateless-auth-db:
      container_name: stateless-auth-db
      image: postgres:latest
      environment: 
        POSTGRES_DB: auth-db
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
      networks:
        - auth   
      ports:
        - "5432:5432"   

    stateful-auth-db:
      container_name: stateful-auth-db
      image: postgres:latest
      environment: 
        POSTGRES_DB: auth-db
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
      networks:
        - auth     
      ports:
        - "5433:5432"  

    token-redis:
      container_name: token-redis
      image: redis:latest
      networks:
       - auth  
      ports:
        - "6379:6379"  

    stateless-auth-api:
      build: './stateless/stateless-auth-api'
      container_name: stateless-auth-api
      depends_on:
        - stateless-auth-db
     
      networks:
        - auth
      environment:
        - DB_HOST=stateless-auth-db
        - DB_NAME=auth-db
        - DB_USER=admin
        - DB_PASSWORD=admin
        - DB_PORT=5432
      ports:
        - 8080:8080  

    stateless-any-api:
      build: './stateless/stateless-any-api'
      container_name: stateless-any-api
      depends_on:
        - stateless-auth-db
      networks:
        - auth
      ports:
        - 8081:8081

    stateful-auth-api:
      build: './stateful/stateful-auth-api'
      container_name: stateful-auth-api
      depends_on:
        - stateful-auth-db
      networks:
        - auth
      environment:
        - DB_HOST=stateful-auth-db
        - DB_NAME=auth-db
        - DB_USER=admin
        - DB_PASSWORD=admin
        - DB_PORT=5432
      ports:
        - 8082:8082 
        
    stateful-any-api:
      build: './stateful/stateful-any-api'
      container_name: stateful-any-api
      networks:
        - auth
      ports:
        - 8083:8083                     

networks:
  auth: 
     driver: bridge
        